export const CATEGORY_DEFINITIONS = `
- **Regulatory Updates**: Announcements from regulatory bodies like the FDA, EMA (e.g., approvals, rejections, new guidelines, clinical trial holds).
- **Commercial & Market Access**: News related to sales, marketing, pricing, reimbursement, and product launches.
- **Legal & IP Developments**: Updates on patent litigation, settlements, intellectual property disputes, and antitrust cases.
- **Financial & Corporate**: Information about mergers & acquisitions (M&A), partnerships, licensing deals, quarterly earnings, stock performance, and executive leadership changes.
- **Conference & Research**: Publication of clinical trial data, R&D updates, and presentations at major medical conferences.
- **Uncategorized**: For articles that do not fit neatly into the above categories.
`;

export const INITIAL_MONITORED_COMPANIES: string[] = [
  "AbbVie",
  "Abbott",
  "Accord",
  "Adello",
  "Alexion",
  "Alteogen",
  "Alvotech",
  "Amgen",
  "Amneal",
  "Apotex",
  "Apobiologix",
  "Archigen",
  "AstraZeneca",
  "Aurobindo",
  "Bayer",
  "Beyond Spring",
  "Bio-Thera",
  "Biocon",
  "Biocon Biologics",
  "BioFacutura",
  "Biogen",
  "Biointegrat",
  "bioXpress",
  "Boan Biotech",
  "Boehringer Ingelheim",
  "BMS",
  "Celltrion",
  "Civica",
  "Coherus",
  "Curateq",
  "Daiichi Sankyo",
  "Dong-A",
  "Dr. Reddy's",
  "Eden Biologics",
  "Enzene Biosciences A",
  "Evive Biotech",
  "Formycon",
  "Fresenius Kabi",
  "Fuji Pharma",
  "Fujifilm",
  "G1 Therapeutics",
  "Gedeon Richter",
  "Gedon Richter",

  "Genentech",
  "GE Healthcare",
  "Henlius",
  "Hetero",
  "Hikma",
  "iBio",
  "Innovent",
  "Intas",
  "J&J",
  "JAMP Pharma",
  "Kashiv",
  "Lannett",
  "LG Chem",
  "Lupin",
  "Luye Pharma",
  "Mabion",
  "Mabwell",
  "mabXience",
  "Meiji",
  "Meitheal Pharma",
  "Merck",
  "MiGenTra",
  "MinaPharm Pharmaceuticals",
  "Momenta Pharmaceuticals",
  "Mundipharma",
  "Mycenax-Gedeon",
  "Mylan",
  "NeuClone",
  "Novartis",
  "Novo Nordisk",
  "OncoC4",
  "OPKO Health",
  "Organon",
  "Outlook Therapeutics",
  "Pfizer",
  "Prestige",
  "Protheragen",
  "Qyuns",
  "Rani Therapeutics",
  "Ratiopharm",
  "Regeneron",
  "Roche",
  "Rophibio",
  "Sagent",
  "Sam Chun Dang",
  "Samsung Bioepis",
  "Samsung Biologics",
  "Sandoz",
  "Similis Bio",
  "Sorrento",
  "Spectrum",
  "STADA",
  "Tanvex",
  "Teva",
  "UCB",
  "UndBio",
  "USV",
  "Viatris",
  "Xbrane"
];

export const INITIAL_MONITORED_KEYWORDS: string[] = [
  "351(k)",
  "AbbVie",
  "Abbott",
  "Abevmy",
  "abobotulinumtoxinA",
  "Abrilada",
  "abstract",
  "Accofil",
  "Accord",
  "Actemra",
  "Active, not recruiting",
  "Acute Lymphoblastic Leukemia",
  "Acute Myeloid Leukemia",
  "adalimumab",
  "adalimumab-adbm",
  "adalimumab-afzb",
  "adalimumab-atto",
  "adalimumab-bwwd",
  "Addison's disease",
  "Adello",
  "ADMELOG",
  "ado-trastuzumab emtansine",
  "Advisory Committee",
  "aflibercept",
  "Afolia",
  "Age-Related Macular Degeneration",
  "agreement",
  "Alexion",
  "Alteogen",
  "Alvotech",
  "Alymsys",
  "Amgen",
  "Amgevita",
  "Amjevita",
  "Amneal",
  "Amsparity",
  "ANDA filing",
  "Apotex",
  "Apobiologix",
  "approval",
  "Archigen",
  "Articles",
  "ASCO",
  "ASH",
  "Asia",
  "AstraZeneca",
  "Asthma",
  "Autoimmune",
  "Autoimmune vasculitis",
  "Aurobindo",
  "Avastin",
  "AVSOLA",
  "Aybintio",
  "Basaglar",
  "Bayer",
  "Benepali",
  "bevacizumab",
  "bevacizumab-awwb",
  "bevacizumab-bvzr",
  "bevacizumab-maly",
  "Beyond Spring",
  "biobetter",
  "Biocon",
  "Biocon Biologics",
  "BioFacutura",
  "Biogen",
  "biogeneric",
  "Biointegrat",
  "biologic competition",
  "Biologic License Application",
  "biological license application",
  "biologic patent expiry",
  "biologics",
  "Biosana Pharma",
  "biosimilar",
  "biosimilar approval",
  "biosimilar launch",
  "Biosimilar Solutions (BSS)",
  "biosimilars",
  "BioThera",
  "bioXpress",
  "bimekizumab",
  "Bladder Cancer",
  "BLA",
  "BLA submission",
  "BMS",
  "Boan Biotech",
  "Boehringer Ingelheim",
  "Breast cancer",
  "Brenzys",
  "brodalumab",
  "Byooviz",
  "Cancer",
  "Cavoley",
  "CDSCO",
  "Cegfila",
  "Celiac disease",
  "Celltrion",
  "Central Drug Standard Control Organization",
  "Centre for Pharmaceutical Administration Health Sciences Authority",
  "certolizumab pegol",
  "China",
  "Chronic Lymphocytic Leukemia",
  "Chronic Myelogenous Leukemia",
  "Cimerli",
  "Civica",
  "clazakizumab",
  "clinical endpoint",
  "clinical trial",
  "Coherus",
  "Colon Cancer",
  "Colorectal Cancer",
  "commercialization",
  "Completed",
  "conference",
  "congress",
  "corporate deals",
  "Cosela",
  "Cosentyx",
  "coverage decision",
  "Curateq",
  "Cyltezo",
  "Daiichi Sankyo",
  "Danish Medicines Agency",
  "Darzalex",
  "denosumab",
  "daxibotulinumtoxinA",
  "Daxxify",
  "denosumab",
  "Diabetes",
  "Diabetic Macular Edema",
  "Diabetic Retinopathy",
  "distribution partnership",
  "dividend",
  "Dong-A",
  "Dr. Reddy's",
  "Dry Eye",
  "DS-8201",
  "earnings",
  "EC",
  "Eculizumab",
  "Eden Biologics",
  "efbemalenograstim alfa",
  "eflapegrastim",
  "eflapegrastim-xnst",
  "Efgratin",
  "Efficacy",
  "EMA",
  "EMA approval",
  "Enbrel",
  "Endocrinology",
  "Endometrial cancer",
  "Endometriosis",
  "Enhertu",
  "Enrolling by invitation",
  "Enzene Biosciences A",
  "epoetin",
  "epoetin alfa",
  "Erelzi",
  "Erosion",
  "ESMO",
  "etanercept",
  "etanercept-ykro",
  "Eticovo",
  "EU",
  "Europe",
  "European Medicines Agency",
  "Events",
  "Evive Biotech",
  "exclusivity",
  "exclusivity period",
  "Eye",
  "Eylea",
  "fam-trastuzumab deruxtecan-nxki",
  "Fatty liver",
  "FDA",
  "FDA approval",
  "Fibromyalgia",
  "filgrastim",
  "filgrastim-aafi",
  "filgrastim-ayow",
  "filgrastim-sndz",
  "Filkri",
  "filgotinib",
  "financial guidance",
  "FIASP",
  "Flixabi",
  "follow-on biologic",
  "Food and Drug Administration",
  "Formycon",
  "formulary",
  "formulary placement",
  "Fresenius Kabi",
  "Fuji Pharma",
  "Fujifilm",
  "Fulphila",
  "Fylnetra",
  "G1 Therapeutics",
  "Gastrointestinal Stromal Tumors",
  "Gazyva",
  "Gazyvaro",
  "G-CSF",
  "Gedeon Richter",
  "general earnings",
  "generic biologic",
  "Genentech",
  "Glatopa",
  "Glaucoma",
  "glatiramer acetate",
  "Glatiramer Acetate Injection",
  "golimumab",
  "Granix",
  "Grastofil",
  "Grasustek",
  "Graves' disease",
  "Graves’ Eye Disease",
  "guidance",
  "Hadlima",
  "hGH-CTP",
  "Hashimoto’s thyroiditis",
  "Head and Neck Cancer",
  "Health Canada",
  "Healthcare",
  "Henlius",
  "Herceptin",
  "Herzuma",
  "Hervelous",
  "Hetero",
  "high concentration formulation",
  "Hikma",
  "hiring",
  "Hodgkin’s lymphoma",
  "Hukyndra",
  "Hulio",
  "Humira",
  "Hyrimoz",
  "iBio",
  "Idacio",
  "Immunology",
  "Imraldi",
  "incobotulinumtoxinA",
  "indication approval",
  "infliximab",
  "infliximab-abda",
  "infliximab-axxq",
  "infliximab-dyyb",
  "infliximab-qbtx",
  "Inflectra",
  "infringement",
  "injunction",
  "Innovent",
  "Intas",
  "intellectual property",
  "interchangeable biologic",
  "interchangeable biosimilar",
  "International Conference on Harmonization",
  "intrahepatic bile duct cancer",
  "Investor",
  "IP Challenges",
  "ixekizumab",
  "J&J",
  "JAMP Pharma",
  "Japan",
  "job opening",
  "Kadcyla",
  "Kanjinti",
  "Kashiv",
  "Kevzara",
  "label expansion",
  "lanadelumab",
  "Lannett",
  "Lantus",
  "Lapelga",
  "launch",
  "lawsuits",
  "legal settlements",
  "Leukemia",
  "LEVEMIR",
  "LG Chem",
  "Libmyris",
  "License",
  "licensing deal",
  "Lifmior",
  "litigation",
  "Liver Cancer",
  "long-acting C-peptide",
  "long-acting GLP-2",
  "LUCENTIS",
  "Lung cancer",
  "Lupin",
  "Lupus",
  "Lupus SLE",
  "Luye Pharma",
  "Mabion",
  "MabThera",
  "Mabwell",
  "mabXience",
  "Macular Edema",
  "market access",
  "Marketing Authorization Application",
  "M-and-A Activity",
  "Meiji",
  "Meitheal Pharma",
  "Melanoma",
  "Merck",
  "Metastatic Cancer",
  "MHRA",
  "MiGenTra",
  "milestone payment",
  "MinaPharm Pharmaceuticals",
  "Ministry of Health",
  "Ministry of Health, Labour & Welfare",
  "Momenta Pharmaceuticals",
  "monoclonal antibody",
  "Multiple sclerosis",
  "Mundipharma",
  "Mvasi",
  "Myasthenia gravis",
  "Mycenax-Gedeon",
  "Mylan",
  "Natalizumab",
  "Nepexto",
  "Neulasta",
  "Neupogen",
  "NeuClone",
  "Neuroblastoma",
  "Neovascular Age-Related Macular Degeneration",
  "New Drug Application",
  "Nivestim",
  "Nivestym",
  "NMPA",
  "Non-Hodgkin’s lymphoma",
  "Non-Small Cell Lung Cancer",
  "Novartis",
  "Novo Nordisk",
  "Novolog",
  "Nyvepria",
  "Obesity",
  "obinutuzumab",
  "ocular",
  "office opening",
  "Ogivri",
  "Olumiant",
  "Omalizumab",
  "on-body device",
  "on-body injector",
  "Onbevzi",
  "Oncology",
  "OncoC4",
  "Onpattro",
  "Ontruzant",
  "OPKO Health",
  "Opdivo",
  "Ophthalmology",
  "Optha",
  "Orencia",
  "Organon",
  "originator biologic",
  "Osteoarthritis",
  "Otezla",
  "Outlook Therapeutics",
  "Ovarian Cancer",
  "Oyavas",
  "Pan American Health Organization",
  "Pancreatic Cancer",
  "partnership deals",
  "patent",
  "patent challenge",
  "patent litigation",
  "patisiran",
  "patients",
  "payer",
  "payer coverage",
  "PDUFA date",
  "pegfilgrastim",
  "pegfilgrastim-apgf",
  "pegfilgrastim-bmez",
  "pegfilgrastim-cbqv",
  "pegfilgrastim-fpgk",
  "pegfilgrastim-jmdb",
  "pegfilgrastim-pbbk",
  "Pelgraz",
  "Pelmeg",
  "Perjeta",
  "Pernicious anemia",
  "pertuzumab",
  "Pfizer",
  "Phase 1",
  "Phase 2",
  "Phase 3",
  "Phase Early Phase 1",
  "Phase III",
  "Phase III results",
  "Phesgo",
  "Pink Eye",
  "Pipeline",
  "plinabulin",
  "poster",
  "preferred status",
  "Presbyopia",
  "Presentation",
  "Prestige",
  "Price",
  "pricing",
  "Procrit",
  "product launches",
  "Prolia",
  "Prostate cancer",
  "Protheragen",
  "Psoriasis",
  "Psoriatic arthritis",
  "Purple Book",
  "Qyuns",
  "Rani Therapeutics",
  "ranibizumab",
  "ranibizumab-nuna",
  "Rare Diseases",
  "Ratiopharm",
  "rebate",
  "Rectal cancer",
  "reference biologic",
  "reference product",
  "Regeneron",
  "regulatory filing",
  "regulatory milestone",
  "Rekovelle",
  "Releuko",
  "Remicade",
  "Renal Cell Carcinoma",
  "Renflexis",
  "research publications",
  "Retinitis Pigmentosa",
  "Retinoblastoma",
  "Retinopathy",
  "revenue",
  "REZVOGLAR",
  "Rheumatoid arthritis",
  "Riabni",
  "Rinvoq",
  "risankizumab",
  "Ristempa",
  "rituximab",
  "rituximab-abbs",
  "rituximab-pvvr",
  "Rituxan",
  "Rixathon",
  "Roche",
  "Rolontis",
  "Rolvedon",
  "Rophibio",
  "routine quarterly",
  "royalty",
  "Ruxience",
  "Ryzneuta",
  "Sagent",
  "sales",
  "Sam Chun Dang",
  "Samsung Bioepis",
  "Samsung Biologics",
  "Sandoz",
  "sarilumab",
  "scientific updates",
  "secukinumab",
  "Semglee",
  "settlement",
  "Shingles Herpes Zoster",
  "Similis Bio",
  "Simlandi",
  "Simponi",
  "sirukumab",
  "Sjögren’s syndrome",
  "Skyriq",
  "Soliris",
  "Solymbic",
  "somapacitan",
  "somatrogon",
  "somatropin",
  "Sorrento",
  "Sogroya",
  "Spectrum",
  "STADA",
  "Stargardt Disease",
  "Stelara",
  "Stimufend",
  "stock split",
  "submissions",
  "subsequent entry biologic",
  "supply agreement",
  "Susvimo",
  "switching study",
  "Swissmedic",
  "symposium",
  "Systemic lupus erythematosus",
  "T-DM1",
  "Takeda",
  "Taltz",
  "Tanvex",
  "tbo-filgrastim",
  "tender",
  "Teva",
  "therapeutic equivalence",
  "therapeutic protein",
  "Therapeutic Goods Administration",
  "Thyroid cancer",
  "tildrakizumab",
  "tofacitinib",
  "tocilizumab",
  "Toujeo",
  "Trazimera",
  "trastuzumab",
  "trastuzumab-anns",
  "trastuzumab-dkst",
  "trastuzumab-dttb",
  "trastuzumab-pkrb",
  "trastuzumab-qyyp",
  "Tremfya",
  "trilaciclib",
  "Truxima",
  "Tumor",
  "Tumour",
  "Tuznue",
  "Tysabri",
  "UCB",
  "Udenyca",
  "UndBio",
  "upadacitinib",
  "US",
  "USA",
  "ustekinumab",
  "USV",
  "Uveitis",
  "Vasculitis",
  "Vegzelma",
  "Viatris",
  "Webcast",
  "WHO",
  "World Health Organization",
  "World Intellectual Property Organization",
  "World Trade Organization",
  "Xbrane",
  "Xcimzane",
  "Xeomin",
  "Xeljanz",
  "Xolair",
  "Yuflyma",
  "Yusimry",
  "Zarxio",
  "Zarzio",
  "Zercepac",
  "Zessly",
  "Ziextenzo",
  "Zirabev"
];